apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: testing
spec:
  type: NodePort
  selector:
    app: test-deployment
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30700