apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: test-deployment
    version: 2.0.0
  ports:
    - name: http
      protocol: TCP
      port: 8070
      targetPort: 8070