apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment2
  labels:
    app: test-deployment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-deployment2
  template:
    metadata:
      labels:
        app: test-deployment2
    spec:
      containers:
      - name: hello2
        image: gcr.io/google-samples/hello-app:2.0