apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: testing
  labels:
    app: test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-deployment
      version: 2.0.0
  template:
    metadata:
      labels:
        app: test-deployment
        version: 2.0.0
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
          - containerPort: 8020
