apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployment
  namespace: testing
  labels:
    app: testdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testdeployment
      version: 2.0.0
  template:
    metadata:
      labels:
        app: testdeployment
        version: 2.0.0
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
